### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Hitori#1]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon. The largest icon this currently contains is 48px.

https://gitlab.gnome.org/GNOME/hitori/tree/master/data/icons

@pwithnall what do you reckon?

**Comment by pwithnall** [comment]
I have been waiting for one for a while: https://gitlab.gnome.org/GNOME/hitori/issues/6

**Comment by nedrichards** [comment]
Fair enough!

**Comment by pwithnall** [comment]
Jakub fixed [the issue](https://gitlab.gnome.org/GNOME/hitori/issues/6) with [this commit](https://gitlab.gnome.org/GNOME/hitori/commit/8a5db1f271b7b482f035cc6b45a430213b157be7), so I think this should be resolved from the flatpak side of things next time we upload a flatpak?
